---
title: "mex-cog weighted summary"
output: rmarkdown::github_document
date: "2024-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load libraries
if (!require("pacman")){
  install.packages("pacman", repos='http://cran.us.r-project.org')
}

p_load("janitor", "broom", "tidyverse", "magrittr", "plyr", "haven", "glue", 
       "survey", "labelled", "gtsummary", "srvyr","gt")
```

```{r}
data <- read.csv('/Users/novak/ZhangYS Dropbox/Shared/HCAP/python file/mex-cog.csv')

# only keep respondents with age >= 65 and non-zero sample weights 
data <- data %>% 
  filter(rage >= 65) %>% 
  filter(wgt != 0) %>% 
  drop_na()
```

```{r}
summary_data <- data %>% 
  select(rage, rfemale, reduc, iage, ifemale, ieduc, 
             coresi, ispouse, ichild, iothfam, inonfam, wgt)

# only individual sample weights for now 
svydes <- summary_data %>% 
  as_survey_design(
    weights = wgt
  )
```

```{r}
create_wtgsumm <- function(vars) {
  svydes %>% 
    tbl_svysummary(
      include = all_of(vars),  
      type = list(all_continuous() ~ "continuous2"),
      statistic = list(
        all_continuous() ~ c("{mean}", "({sd})", "{median}", "({p25}, {p75})"),
        all_categorical() ~ "{n} ({p}%)"
      ), 
      digits = list(all_continuous() ~ 2, all_categorical() ~ c(0, 1))
    ) %>% 
    bold_labels()  # No add_overall() if no grouping
}
```

```{r}
create_wtgsumm(c('rage', 'rfemale', 'reduc', 'iage', 'ifemale', 'ieduc', 
             'coresi', 'ispouse', 'ichild', 'iothfam', 'inonfam'))
```








